### ISSUE TITLE
leak header file.

### ISSUE THREAD

**Issue by xuhancn** [Unsigned-Long/pretty-table#1]
/home/xu/test/pretty-table/main.cpp:1:10: fatal error: artwork/geometry/point.hpp: No such file or directory
    1 | #include "artwork/geometry/point.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Unsigned-Long** [comment]
This header file is the file of another project (you can find it in my project list), which is only used to test the table printing of this library. So don't worry about this file. Just delete it directly.

**Comment by Unsigned-Long** [comment]
Moreover, the table print library only has header files and does not rely on any third-party library. When using, you can only include this header file

**Comment by xuhancn** [comment]
I have solve this issue, and run it on Linux. But some issue on Windows.

https://github.com/Unsigned-Long/pretty-table/blob/master/src/include/prettytable.hpp#L175
Error:
---------------------------------------
1>C:\Users\xu\Desktop\pretty-table-master\include\prettytable.hpp(175): error C2015: too many characters in constant

**Comment by Unsigned-Long** [comment]
![image](https://user-images.githubusercontent.com/76953144/158066672-0cc37eab-dff3-4d85-a09f-c400d3b7a0f2.png)
Sorry, I wrote this library on Ubuntu before, but I haven't tested it under windows. Now I try and find the problem in the following figure:
![image](https://user-images.githubusercontent.com/76953144/158066764-5910d821-f89a-4981-a4d4-e52b67f1567f.png)
Just remove the single quotation marks.

**Comment by xuhancn** [comment]
> ![image](https://user-images.githubusercontent.com/76953144/158066672-0cc37eab-dff3-4d85-a09f-c400d3b7a0f2.png) Sorry, I wrote this library on Ubuntu before, but I haven't tested it under windows. Now I try and find the problem in the following figure: ![image](https://user-images.githubusercontent.com/76953144/158066764-5910d821-f89a-4981-a4d4-e52b67f1567f.png) Just remove the single quotation marks.

Thanks.
